config/routes.rb
NEMT::Application.routes.draw do
  root "pages#members"
  get "reports" => "pages#reports"
  get "providers" => "pages#providers"
  get "policies" => "pages#policies"
  get "help" => "pages#help"
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def members
  end

  def reports
  end

  def providers
  end

  def policies
  end

  def help
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> <%= link_to " Members", root_path %> </li>
        <li> <%= link_to " Providers", providers_path %> </li>
        <li> <%= link_to " Reports/Analytics", reports_path %> </li>
        <li> <%= link_to " Policies and Procedures", policies_path %> </li>
        <li> <%= link_to " Help", help_path %> </li>

      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Logout</a></li>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NEMT</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>
   <%= yield %>

</body>
</html>

app/views/pages/members.html.erb
<!DOCTYPE html>
<html >
<head>
<title>members page</title>

</head>
 
<body >
	<div class="container">
		<div class="btn-group">
	  	<button type="button" class="btn btn-default">Left</button>
	  	<button type="button" class="btn btn-default">Middle</button>
	  	<button type="button" class="btn btn-default">Right</button>
		</div>
		<p> welcome home</p>
	</div>
</body>
</html>